### ISSUE TITLE
Are multiple consumers supported?

### ISSUE THREAD

**Issue by Gouthamve** [bogdanovich/siberite#15]
Hi, I am very new to queues and am going to use siberite for a project. While now one consumer will be sufficient, there might be need to add multiple consumers.

Your TODO has: Add multiple consumers ```get queue_name:consumer_name/open```

Does this mean now only one consumer is supported? If I connect two consumers what is going to happen.

**Comment by bogdanovich** [comment]
Multiple **consumer groups** are not supported right now. That means you can't read one queue many times starting from the head again and again. But of course you can have many clients reading from one queue.

**Comment by Gouthamve** [comment]
Thanks!! Started using it :) Like it so far

Also is there anyway I can see the **number** of messages in the queue?

**Comment by bogdanovich** [comment]
You can use `stats` command.
`STAT queue_<queue_name>_items 55614776` - shows the number of items
