### ISSUE TITLE
A Siberite Specific Client

### ISSUE THREAD

**Issue by Gouthamve** [bogdanovich/siberite#23]
Do you already have a Go siberite client, or should I start working on one?

While the memcache clients are good enough, with the addition of multiple consumer groups and the subcommands, I think siberite could use a custom client.

Also I find the existing Go Memcache clients are not implementing all the commands, specifically, stats and others.

**Comment by bogdanovich** [comment]
Not yet, it's only in plans.
You are welcome to start working on it of course.
