### ISSUE TITLE
server errors when connecting from siberite-ruby client

### ISSUE THREAD

**Issue by tlossen** [bogdanovich/siberite#36]
when connecting from ruby and issuing simple sets / gets in a loop, i see lots of errors in the server log:

> 2017/01/20 17:59:25 [::1]:49381 ERROR Unknown command
> 2017/01/20 17:59:25 [::1]:49392 ERROR Unknown command
> 2017/01/20 17:59:25 [::1]:49394 ERROR Unknown command
> 2017/01/20 17:59:25 [::1]:49398 ERROR Unknown command

(probably a client issue, but the other repo doesn't have issues enabled.)

**Comment by bogdanovich** [comment]
Enabled issues for siberite-client. Will check it over the weekend

**Comment by tlossen** [comment]
cool, thanks! to clarify: i was using two client instances from two separate threads.

**Comment by tlossen** [comment]
ok, i'll close this and open an issue in the other repo.
